<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\Aaron\Documents\FunBit\static\models\Character_Male_1.gltf --root /Cube-World/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName =
    | 'Death'
    | 'Duck'
    | 'HitReact'
    | 'Idle'
    | 'Idle_Attack'
    | 'Idle_Hold'
    | 'Jump'
    | 'Jump_Idle'
    | 'Jump_Land'
    | 'No'
    | 'Punch'
    | 'Run'
    | 'Run_Attack'
    | 'Run_Hold'
    | 'Walk'
    | 'Walk_Hold'
    | 'Wave'
    | 'Yes'
  type GLTFResult = {
    nodes: {
      Character: THREE.SkinnedMesh
      Root: THREE.Bone
    }
    materials: {
      Atlas: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/Cube-World/Character_Male_1.gltf')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="CharacterArmature">
        <T is={gltf.nodes.Root} />
        <T.SkinnedMesh
          name="Character"
          geometry={gltf.nodes.Character.geometry}
          material={gltf.materials.Atlas}
          skeleton={gltf.nodes.Character.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
