<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\Aaron\Documents\FunBit\static\models\Rail_Corner.gltf --root /Cube-World/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube551: THREE.Mesh
      Cube551_1: THREE.Mesh
    }
    materials: {
      ['Material.002']: THREE.MeshStandardMaterial
      Atlas: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/Cube-World/Rail_Corner.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube551.geometry} material={gltf.materials['Material.002']} />
    <T.Mesh geometry={gltf.nodes.Cube551_1.geometry} material={gltf.materials.Atlas} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
