<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\Aaron\Documents\FunBit\static\models\Skeleton_Armor.gltf --root /Cube-World/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Attack' | 'Death' | 'HitRecieve' | 'Idle' | 'Jump' | 'Run' | 'Walk'
  type GLTFResult = {
    nodes: {
      Cube287: THREE.SkinnedMesh
      Cube287_1: THREE.SkinnedMesh
      Skeleton: THREE.SkinnedMesh
      Root: THREE.Bone
    }
    materials: {
      ['Atlas.003']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      Atlas: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/Cube-World/Skeleton_Armor.gltf')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="EnemyArmature">
        <T is={gltf.nodes.Root} />
        <T.Group name="Armor">
          <T.SkinnedMesh
            name="Cube287"
            geometry={gltf.nodes.Cube287.geometry}
            material={gltf.materials['Atlas.003']}
            skeleton={gltf.nodes.Cube287.skeleton}
          />
          <T.SkinnedMesh
            name="Cube287_1"
            geometry={gltf.nodes.Cube287_1.geometry}
            material={gltf.materials['Material.002']}
            skeleton={gltf.nodes.Cube287_1.skeleton}
          />
        </T.Group>
        <T.SkinnedMesh
          name="Skeleton"
          geometry={gltf.nodes.Skeleton.geometry}
          material={gltf.materials.Atlas}
          skeleton={gltf.nodes.Skeleton.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
