<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\Aaron\Documents\FunBit\static\models\Wolf.gltf --root /Cube-World/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Death' | 'Headbutt' | 'Idle' | 'Idle_Eating' | 'Jump_Loop' | 'Jump_Start' | 'Run' | 'Walk'
  type GLTFResult = {
    nodes: {
      Wolf: THREE.SkinnedMesh
      All: THREE.Bone
      Root: THREE.Bone
    }
    materials: {
      Atlas: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/Cube-World/Wolf.gltf')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="AnimalArmature">
        <T is={gltf.nodes.All} />
        <T is={gltf.nodes.Root} />
        <T.SkinnedMesh
          name="Wolf"
          geometry={gltf.nodes.Wolf.geometry}
          material={gltf.materials.Atlas}
          skeleton={gltf.nodes.Wolf.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
