<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\Aaron\Documents\FunBit\static\models\BirchTree_5.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Cube009: THREE.Mesh;
			Cube009_1: THREE.Mesh;
		};
		materials: {
			BirchTree_Bark: THREE.MeshStandardMaterial;
			BirchTree_Leaves: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/Ultimate-Stylized-Nature/BirchTree_5.gltf');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Cube009.geometry} material={gltf.materials.BirchTree_Bark} />
		<T.Mesh geometry={gltf.nodes.Cube009_1.geometry} material={gltf.materials.BirchTree_Leaves} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
