<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\Aaron\Documents\FunBit\static\models\Bush_Large_Flowers.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useTexture } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Plane029: THREE.Mesh;
			Plane029_1: THREE.Mesh;
		};
		materials: {
			Bush_Leaves: THREE.MeshStandardMaterial;
			Flowers: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/Ultimate-Stylized-Nature/Bush_Large_Flowers.gltf');
	const texture1 = useTexture('/Ultimate-Stylized-Nature/Textures/Bush_Leaves.png');
	const texture2 = useTexture('/Ultimate-Stylized-Nature/Textures/Flowers.png').then((texture) => {
		// Different offsets produce different flowers.
		texture.offset = new THREE.Vector2(0.41, 0.61);
		return texture;
	});

	const assets = Promise.all([gltf, texture1, texture2]);

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await assets}
		<slot name="fallback" />
	{:then [gltf, t1, t2]}
		<T.Group rotation={[2.02, 0.22, -0.51]}>
			<T.Mesh geometry={gltf.nodes.Plane029.geometry}>
				<T.MeshStandardMaterial map={t1} alphaTest={0.2} />
			</T.Mesh>
			<T.Mesh geometry={gltf.nodes.Plane029_1.geometry}>
				<T.MeshStandardMaterial map={t2} alphaTest={0.2} />
			</T.Mesh>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
