<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\blah\Documents\FunBit\static\Ultimate-Stylized-Nature\Bush_Large_Flowers.gltf --root /Ultimate-Stylized-Nature/ --types --printwidth 120 --precision 2 --suspense
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Vector2 } from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useSuspense, useTexture } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			Plane029: THREE.Mesh;
			Plane029_1: THREE.Mesh;
		};
		materials: {
			Bush_Leaves: THREE.MeshStandardMaterial;
			Flowers: THREE.MeshStandardMaterial;
		};
	};

	const gltf = suspend(useGltf<GLTFResult>('/Ultimate-Stylized-Nature/Bush_Large_Flowers.gltf'));
	const texture1 = suspend(useTexture('/Ultimate-Stylized-Nature/Textures/Bush_Leaves.png'));
	const texture2 = suspend(
		useTexture('/Ultimate-Stylized-Nature/Textures/Flowers.png').then((texture) => {
			// Different offsets produce different flowers.
			texture.offset = new Vector2(0.41, 0.61);
			return texture;
		})
	);

	const assets = Promise.all([gltf, texture1, texture2]);
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await assets}
		{@render fallback?.()}
	{:then [gltf, t1, t2]}
		<T.Group rotation={[2.02, 0.22, -0.51]}>
			<T.Mesh geometry={gltf.nodes.Plane029.geometry}>
				<T.MeshStandardMaterial map={t1} alphaTest={0.2} />
			</T.Mesh>
			<T.Mesh geometry={gltf.nodes.Plane029_1.geometry}>
				<T.MeshStandardMaterial map={t2} alphaTest={0.2} />
			</T.Mesh>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
