<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\blah\Documents\FunBit\static\Ultimate-Stylized-Nature\MapleTree_2.gltf --root /Ultimate-Stylized-Nature/ --types --printwidth 120 --precision 2 --suspense
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { RepeatWrapping, DoubleSide } from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useSuspense, useTexture } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			Cube009: THREE.Mesh;
			Cube009_1: THREE.Mesh;
		};
		materials: {
			MapleTree_Bark: THREE.MeshStandardMaterial;
			MapleTree_Leaves: THREE.MeshStandardMaterial;
		};
	};

	const gltf = suspend(useGltf<GLTFResult>('/Ultimate-Stylized-Nature/MapleTree_2.gltf'));
	const texture1 = suspend(useTexture('/Ultimate-Stylized-Nature/Textures/MapleTree_Bark.png'));
	const normalMap1 = suspend(
		useTexture('/Ultimate-Stylized-Nature/Textures/MapleTree_Bark_Normal.png')
	);
	const texture2 = suspend(useTexture('/Ultimate-Stylized-Nature/Textures/MapleTree_Leaves.png'));

	const assets = Promise.all([gltf, texture1, normalMap1, texture2]);
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await assets}
		{@render fallback?.()}
	{:then [gltf, t1, n1, t2]}
		<T.Mesh geometry={gltf.nodes.Cube009.geometry}>
			<T.MeshStandardMaterial
				map={t1}
				map.wrapS={RepeatWrapping}
				map.wrapT={RepeatWrapping}
				normalMap={n1}
				normalMap.wrapS={RepeatWrapping}
				normalMap.wrapT={RepeatWrapping}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube009_1.geometry}>
			<T.MeshStandardMaterial map={t2} side={DoubleSide} alphaTest={0.5} />
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
