<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\blah\Documents\FunBit\static\Ultimate-Stylized-Nature\Petals_3.gltf --root /Ultimate-Stylized-Nature/ --types --printwidth 120 --precision 2 --suspense
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { DoubleSide } from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useSuspense, useTexture } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			Petals_3: THREE.Mesh;
		};
		materials: {
			Flowers: THREE.MeshStandardMaterial;
		};
	};

	const gltf = suspend(useGltf<GLTFResult>('/Ultimate-Stylized-Nature/Petals_3.gltf'));
	const texture1 = suspend(
		useTexture('/Ultimate-Stylized-Nature/Textures/Flowers.png').then((texture) => {
			return texture.clone();
		})
	);

	const assets = Promise.all([gltf, texture1]);
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await assets}
		{@render fallback?.()}
	{:then [gltf, t1]}
		<T.Mesh geometry={gltf.nodes.Petals_3.geometry} rotation={[2.26, -0.53, -1.01]}>
			<T.MeshStandardMaterial side={DoubleSide} alphaTest={0.5}>
				<T is={t1} attach="map" offset={[0, 0.2]} />
			</T.MeshStandardMaterial>
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
