<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\Aaron\Documents\FunBit\static\models\PineTree_4.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useTexture } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Cube014: THREE.Mesh;
			Cube014_1: THREE.Mesh;
		};
		materials: {
			PineTree_Bark: THREE.MeshStandardMaterial;
			PineTree_Leaves: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/Ultimate-Stylized-Nature/PineTree_4.gltf');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await assets}
		<slot name="fallback" />
	{:then [gltf, t1, n1, t2]}
		<T.Mesh geometry={gltf.nodes.Cube014.geometry} material={gltf.materials.PineTree_Bark} />
		<T.Mesh geometry={gltf.nodes.Cube014_1.geometry} material={gltf.materials.PineTree_Leaves} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
