<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\Aaron\Documents\FunBit\static\models\Plant_2.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useTexture } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Plant_2: THREE.Mesh;
		};
		materials: {
			Flowers: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/Ultimate-Stylized-Nature/Plant_2.gltf');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await assets}
		<slot name="fallback" />
	{:then [gltf, t1]}
		<T.Mesh
			geometry={gltf.nodes.Plant_2.geometry}
			material={gltf.materials.Flowers}
			rotation={[0.12, 0, 0]} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
